[servers]
loadbalancer ansible_host=192.168.56.11
webserver1 ansible_host=192.168.56.12
webserver2 ansible_host=192.168.56.13
appserver ansible_host=192.168.56.14

[servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'