Vagrant.configure("2") do |config|

  servers = {
    "loadbalancer" => "192.168.56.11",
    "webserver1" => "192.168.56.12",
    "webserver3" => "192.168.56.13",
    "appserver" => "192.168.56.14"
  }

  servers.each do |name, ip|
    config.vm.define name do |node|
      # Use an x86-64 compatible Ubuntu 22.04 box for Windows/Intel
      node.vm.box = "ubuntu/jammy64" 
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      # Use VirtualBox instead of QEMU
      node.vm.provider "virtualbox" do |vb|
        if name == "appserver"
          vb.memory = "2048"
        else
          vb.memory = "1024"
        end
        vb.cpus = name == "loadbalancer" ? "2" : "1"
      end
    end
  end
  
end