[servers]
loadbalancer ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/loadbalancer/qemu/private_key
webserver1 ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/webserver1/qemu/private_key
webserver3 ansible_host=192.168.56.13 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/webserver3/qemu/private_key
appserver ansible_host=192.168.56.14 ansible_user=vagrant ansible_ssh_private_key_file=.vagrant/machines/appserver/qemu/private_key

[servers:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'