Vagrant.configure("2") do |config|
  servers = [
    ["loadbalancer", "192.168.56.11", 50022],
    ["webserver1", "192.168.56.12", 50023],
    ["webserver2", "192.168.56.13", 50024],
    ["appserver", "192.168.56.14", 50025],
  ]

  servers.each do |name, ip, ssh_port|
    config.vm.define name do |node|
      node.vm.box = "perk/ubuntu-2204-arm64"
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip
      
#Overriding Vagrant's core default 50022 SSH mapping
      node.vm.network "forwarded_port", guest: 22, host: ssh_port, id: "ssh", auto_correct: true

      node.vm.provider "qemu" do |qe|
        qe.ssh_port = ssh_port
        qe.memory = name == "appserver" ? "2G" : "1G"
        qe.cpu_count = name == "loadbalancer" ? "2" : "1"
      end
    end
  end
end